# Generated by Django 3.1.3 on 2022-02-03 17:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('receipt_number', models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False)),
                ('status_of_delivery', models.CharField(choices=[('posting', 'Posting'), ('posted', 'Posted'), ('delivering', 'Delivering'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='posting', max_length=50)),
                ('delivery_rate_charge', models.CharField(choices=[('2KM Or Less', '2KM Or Less'), ('2km - 4km', '2km - 4km'), ('4KM Or More', '4KM Or More')], default='2KM Or Less', max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('information', models.CharField(max_length=255)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.restaurant')),
            ],
        ),
    ]
