# Generated by Django 3.1.3 on 2022-02-03 18:23

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='posted_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='receipt_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
