# Generated by Django 3.1.3 on 2022-02-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220203_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='distance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='delivery',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='delivery',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
