# Generated by Django 3.1.3 on 2022-02-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220214_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
