# Generated by Django 3.1.3 on 2022-02-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_restaurant_restaurant_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_address_lattiude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_address_longitude',
            field=models.FloatField(default=0),
        ),
    ]
