# Generated by Django 3.1.3 on 2022-02-14 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220214_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='restaurant_address_lattiude',
            new_name='restaurant_address_latitude',
        ),
    ]
