# Generated by Django 3.1.3 on 2022-02-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20220215_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_address_latitude',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
