# Generated by Django 3.1.3 on 2022-02-17 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_delivery_store_restaurant_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_rate_charge',
        ),
    ]
