# Generated by Django 3.1.3 on 2022-03-06 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20220306_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='id',
            new_name='receipt_number',
        ),
    ]
