# Generated by Django 3.1.3 on 2022-03-20 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20220320_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='driver',
        ),
    ]
