# Generated by Django 3.1.3 on 2022-04-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_delivery_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivered_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
