# Generated by Django 3.1.3 on 2022-04-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_delivery_delivered_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='restaurant_address_lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='delivery',
            name='restaurant_address_lng',
            field=models.FloatField(default=0),
        ),
    ]
