name: Create Tag

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: anothrNick/github-tag-action@1.26.0
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
