name: Create Tag

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: tvdias/github-tagger@v0.0.1
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
